version: '3.8'

services:

  db:
    image: postgres:13
    container_name: db_postgres_toys
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: toys
    
    volumes:
      - db-data:/var/lib/postgresql/data
    
    networks:
      - toys-net

  app:
    build: .
    container_name: app_java_toys
    restart: unless-stopped

    depends_on:
      db:
        condition: service_healthy
        
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/toys
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

    ports:
      - "8080:8080"
      
    networks:
      - toys-net

volumes:
  db-data:

networks:
  toys-net:
    driver: bridge
